version: "3.8"
services:
  mongo:
    image: mongo:7.0.7-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_user
      MONGO_INITDB_ROOT_PASSWORD: local_pass
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
  potgres-etl:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_etl_data:/var/lib/postgresql/data/
  redis:
    image: redis:7.2.0-alpine3.18
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
  pg_etl_data:
  redis_data:
